# -*- coding: utf-8 -*-
"""pair_trading.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jvSkVS5edrFXR7nb1I-WMDj3i7o5DzA0
"""

# pip install refinitiv.data

import pandas as pd
import refinitiv.data as rd
import seaborn as sns
import matplotlib.pyplot as plt

company_list = ['GM' , 'TM', 'F','RIVN.O','HMC','NVDA.O', 'AMD.O','TSM','AAPL.O','NFLX.O','SPY']

rd.open_session()
data = rd.get_data(
    universe = ['TSLA.O'],
    fields = ['TR.TotalReturn1D',
             'TR.CLOSEPRICE.DATE'],
    parameters = {
        'SDate': '2020-03-23',
        'EDate': '2023-11-16',
        'Frq': 'D',
        'RH': 'date'
    }
)
data.set_index('Date', inplace = True)
data.drop(columns = ['Instrument'],inplace = True)
data.columns = ['TSLA.O']
data['TSLA.O'] = data['TSLA.O'].astype('float64')
data.head()

for symbol in company_list:
    rd.open_session()
    com_data = rd.get_data(
        universe = [symbol],
        fields = ['TR.TotalReturn1D',
                 'TR.CLOSEPRICE.DATE'],
        parameters = {
            'SDate': '2020-03-23',
            'EDate': '2023-11-16',
            'Frq': 'D',
            'RH': 'date'
        }
    )
    com_data.set_index('Date', inplace = True)
    com_data.drop(columns = ['Instrument'],inplace = True)
    com_data.columns = [symbol]
    com_data[symbol] = com_data[symbol].astype('float64')
    data = pd.merge(data, com_data, left_index = True, right_index = True, how = 'left')

# data.head()

# data.info()

data.to_csv('companies_data.csv')

df = pd.read_csv('companies_data.csv',index_col = 'Date')

correlation_matrix = df.corr()

# Plot heatmap
plt.figure(figsize=(10, 8))  # Adjust the figure size if needed
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation Heatmap')
plt.show()


